// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNyj61KNUYl2nyWRUivcJtxDzMC3cAieM',
    appId: '1:863259288615:web:13dc76412a141f5f185a02',
    messagingSenderId: '863259288615',
    projectId: 'entryproject-7257d',
    authDomain: 'entryproject-7257d.firebaseapp.com',
    storageBucket: 'entryproject-7257d.appspot.com',
    measurementId: 'G-9484C8J7GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXyM2UO40t9XOK7Hguu-F1uZ0s2Ql4CMY',
    appId: '1:863259288615:android:a8d4955ae9649b84185a02',
    messagingSenderId: '863259288615',
    projectId: 'entryproject-7257d',
    storageBucket: 'entryproject-7257d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI7La7QuTYpPUSmRm2peo5bPClV1lPfbs',
    appId: '1:863259288615:ios:90100bb1e04d4f3b185a02',
    messagingSenderId: '863259288615',
    projectId: 'entryproject-7257d',
    storageBucket: 'entryproject-7257d.appspot.com',
    iosClientId: '863259288615-gt0q7rl9k0sfgkvkppg9h1glf5vcb80p.apps.googleusercontent.com',
    iosBundleId: 'com.example.entryProject',
  );
}
